### ISSUE TITLE
Some minor tweaks to the README

### ISSUE THREAD

**Issue by SteveFeldman** [jleo32/VehicleMPG#1]
Hi Justin,

No major issues to report yet...just some small revisions...
1. No need to reference this is a Contrast project. You did the work, hence you get the credit. If it's cool with you, feel free to remove the reference to us.
2. The only issue I faced was making sure that Mongo was up and running. Everything else worked like a champ...
3. Are you planning on submitting the future enhancements or just commenting that you want them? Let me know and I will keep watching the project.

Regards,

Steve

**Comment by jleo32** [comment]
I removed the reference to contrast.  I added a comment to make sure mongod was running and a reference to how to find it.

I am planning on adding at least one or two enhancements because I think it will tie the project in nicely.

Thank you for the suggestions.
